version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    allow:
      - dependency-type: "all"
