version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "build"
    allowed_updates:
      - match:
          update_type: "all"
