name: Retrocookie
on:
  push:
    branches:
      - main
concurrency: serialize
env:
  TEMPLATE: cookiecutter-hypermodern-python
  PROJECT: cookiecutter-hypermodern-python-instance
jobs:
  skip:
    name: Skip workflow if cutty.json changed
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip.outputs.skip }}
    steps:
      - name: Check out ${{ env.PROJECT }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if cutty.json changed
        id: skip
        run: |
          if git show --pretty= --name-only ${GITHUB_SHA} | grep -Eq '^cutty\.json$'
          then
            echo ::set-output name=skip::true
          else
            echo ::set-output name=skip::false
          fi
  retrocookie:
    name: Retrocookie
    runs-on: ubuntu-latest
    needs: skip
    if: "!fromJSON(needs.skip.outputs.skip)"
    steps:
      - name: Check out ${{ env.PROJECT }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.PROJECT }}
          fetch-depth: 2
      - name: Check out ${{ env.TEMPLATE }}
        uses: actions/checkout@v3
        with:
          repository: "cjolowicz/${{ env.TEMPLATE }}"
          path: ${{ env.TEMPLATE }}
          token: ${{ secrets.X_GITHUB_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install retrocookie
        working-directory: ${{ env.TEMPLATE }}
        run: |
          pip install retrocookie
          retrocookie --version
      - name: Import commit into ${{ env.TEMPLATE }}
        run: |
          retrocookie -C ${TEMPLATE} ${PROJECT} ${GITHUB_SHA} --exclude-variable=copyright_year --exclude-variable=license --exclude-variable=version || status=$?

          if [ $status -ne 0 ]
          then
            if git -C ${TEMPLATE} status --porcelain | grep --fixed-strings --quiet retrocookie.yml
            then
              echo "Resolving conflicts for retrocookie.yml..."
              git -C ${TEMPLATE} rm '{{cookiecutter.project_name}}/.github/workflows/retrocookie.yml'
              git -C ${TEMPLATE} cherry-pick --continue
            else
              exit $status
            fi
          fi

          message="$(git -C ${PROJECT} show --no-patch --format=%B ${GITHUB_SHA} | sed 's/ *(#[0-9]\+)//g')

          Retrocookie-Original-Commit: ${GITHUB_REPOSITORY}@${GITHUB_SHA::7}"

          git -C ${TEMPLATE} commit --amend --message="$message"
        env:
          GIT_COMMITTER_NAME: "GitHub Action"
          GIT_COMMITTER_EMAIL: "action@github.com"
      - name: Push to cjolowicz/${{ env.TEMPLATE }}
        run: |
          git -C $TEMPLATE push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/cjolowicz/$TEMPLATE.git HEAD:main
