name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.9
      if: matrix.python-version == '3.9'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3.9-dev python3.9-distutils python3.9-venv
        python3.9 -m pip install --upgrade pip setuptools
        python3.9 -m venv $HOME/venv-python3.9
        echo "::set-env name=VIRTUAL_ENV::$HOME/venv-python3.9"
        echo "::add-path::$HOME/venv-python3.9/bin"
    - uses: actions/setup-python@v1
      if: matrix.python-version != '3.9'
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install nox==2019.11.9
    - run: pip install poetry==1.0.3
    - run: nox
