name: Tests
on: push
jobs:
  tests:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - id: pip-cache
        shell: python
        run: |
          from pip._internal.locations import USER_CACHE_DIR as dir
          print("::set-output name=dir::{}".format(dir))
      - uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/constraints.txt') }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/constraints.txt') }}-poetry-
            ${{ runner.os }}-pip-
      - run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt nox poetry
      - run: nox --force-color
